# 服务端口
server:
  port: 8082
# 日志级别
logging:
  level:
    root: info


# dubbo的配置
dubbo:
  # dubbo中的服务名称
  application: item-web1
  # dubbo的通讯协议名称
  protocol:
    name: dubbo
  # zookeeper注册中心的地址
  registry:
#    address: 127.0.0.1:2181
    address: 192.168.45.180:2181
  # zookeeper的通讯协议的名称
    protocol: zookeeper
  # dubbo的服务的扫描路径
  base-package: com.bbo.gmall
  # 设置超时时间
  consumer:
    timeout: 600000
  # 设置是否检查服务存在
    check: false
  qos:
    enable: true
    port: 33335
    accept:
      foreign:
        ip: false

spring:
  thymeleaf:
    # 关闭thymeleaf的缓存(热部署)
    cache: false
    # 松校验
    mode: LEGACYHTML5